/**
 * Minimal, dependency-free PDF report writer.
 *
 * Produces a valid PDF 1.4 document from an array of content blocks so the
 * "Generate PDF Report" export works with zero external services.
 */

const PAGE_WIDTH = 595.28; // A4 portrait
const PAGE_HEIGHT = 841.89;
const MARGIN = 48;
const LINE_HEIGHT = 15;
const FONT_REGULAR = 'F1';
const FONT_BOLD = 'F2';

/** Escapes a string for a PDF literal string. */
function escapePdfText(value) {
  return String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/₹/g, 'Rs. ')
    .replace(/[€]/g, 'EUR ')
    .replace(/[£]/g, 'GBP ')
    .replace(/[¥]/g, 'JPY ')
    .replace(/[–—]/g, '-')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[^\x20-\x7e]/g, '');
}

/** Very small word-wrap using an approximate Helvetica width table. */
const CHAR_WIDTH = 0.5;
function wrapText(text, maxWidth, fontSize) {
  const maxChars = Math.max(10, Math.floor(maxWidth / (fontSize * CHAR_WIDTH)));
  const words = String(text ?? '').split(/\s+/).filter(Boolean);
  const lines = [];
  let line = '';
  for (const word of words) {
    if (!line.length) {
      line = word;
    } else if (`${line} ${word}`.length <= maxChars) {
      line += ` ${word}`;
    } else {
      lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : [''];
}

/**
 * Builds a PDF from content blocks.
 * @param {{title: string, subtitle?: string, sections: Array<{heading?: string, rows?: Array<[string,string]> | Array<string>, paragraphs?: string[]}>}} spec
 * @returns {Buffer}
 */
export function buildPdfReport(spec) {
  const pages = [];
  let ops = [];
  let cursorY = PAGE_HEIGHT - MARGIN;

  const ensureSpace = (needed) => {
    if (cursorY - needed < MARGIN) {
      pages.push(ops.join('\n'));
      ops = [];
      cursorY = PAGE_HEIGHT - MARGIN;
    }
  };

  const drawText = (text, { size = 10, bold = false, indent = 0, gap = 4, color } = {}) => {
    const font = bold ? FONT_BOLD : FONT_REGULAR;
    const lines = wrapText(text, PAGE_WIDTH - MARGIN * 2 - indent, size);
    for (const line of lines) {
      ensureSpace(LINE_HEIGHT);
      cursorY -= LINE_HEIGHT;
      const opsParts = [
        'BT',
        `/${font} ${size} Tf`,
        color ? `${color} rg` : '0 0 0 rg',
        `1 0 0 1 ${MARGIN + indent} ${cursorY.toFixed(2)} Tm`,
        `(${escapePdfText(line)}) Tj`,
        'ET',
      ];
      ops.push(opsParts.join('\n'));
    }
    cursorY -= gap;
  };

  const drawRule = () => {
    ensureSpace(8);
    cursorY -= 6;
    ops.push(`0.75 w 0.8 0.8 0.8 RG ${MARGIN} ${cursorY.toFixed(2)} m ${PAGE_WIDTH - MARGIN} ${cursorY.toFixed(2)} l S`);
    cursorY -= 8;
  };

  // Header
  drawText(spec.title || 'DocuFlow AI Report', { size: 20, bold: true, gap: 2 });
  if (spec.subtitle) drawText(spec.subtitle, { size: 10, gap: 8 });
  drawRule();

  for (const section of spec.sections || []) {
    if (section.heading) {
      ensureSpace(40);
      drawText(section.heading, { size: 13, bold: true, gap: 4 });
      drawRule();
    }
    for (const paragraph of section.paragraphs || []) {
      drawText(paragraph, { size: 10, gap: 6 });
    }
    for (const row of section.rows || []) {
      const [label, value] = Array.isArray(row) ? row : ['', String(row)];
      if (label) drawText(`${label}: ${value}`, { size: 10, indent: 8, gap: 3 });
      else drawText(String(value), { size: 10, indent: 8, gap: 3 });
    }
    if (section.spacer) cursorY -= section.spacer;
  }

  // Footer note
  ensureSpace(60);
  cursorY -= 12;
  drawRule();
  drawText(
    'Generated by DocuFlow AI. Extracted values are machine-read and may require human verification.',
    { size: 8, gap: 0, color: '0.45 0.45 0.45' },
  );

  pages.push(ops.join('\n'));

  // ---- Assemble the PDF object graph ----
  const objects = [];
  const pageCount = pages.length;
  const firstPageObj = 3;
  const fontRegularObj = firstPageObj + pageCount * 2;
  const fontBoldObj = fontRegularObj + 1;
  const totalObjects = fontBoldObj;

  objects[1] = `<< /Type /Catalog /Pages 2 0 R >>`;
  const kids = pages.map((_, i) => `${firstPageObj + i * 2} 0 R`).join(' ');
  objects[2] = `<< /Type /Pages /Kids [${kids}] /Count ${pageCount} >>`;

  pages.forEach((content, i) => {
    const pageObj = firstPageObj + i * 2;
    const contentObj = pageObj + 1;
    objects[pageObj] =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH.toFixed(2)} ${PAGE_HEIGHT.toFixed(2)}] ` +
      `/Resources << /Font << /${FONT_REGULAR} ${fontRegularObj} 0 R /${FONT_BOLD} ${fontBoldObj} 0 R >> >> ` +
      `/Contents ${contentObj} 0 R >>`;
    objects[contentObj] = `<< /Length ${Buffer.byteLength(content, 'latin1')} >>\nstream\n${content}\nendstream`;
  });

  objects[fontRegularObj] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>`;
  objects[fontBoldObj] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>`;

  let pdf = '%PDF-1.4\n';
  const offsets = [];
  for (let i = 1; i <= totalObjects; i += 1) {
    offsets[i] = Buffer.byteLength(pdf, 'latin1');
    pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xrefOffset = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${totalObjects + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i <= totalObjects; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${totalObjects + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'latin1');
}

export default buildPdfReport;
